#
# This file is part of GEO Knowledge Hub.
# Copyright 2020-2021 GEO Secretariat.
#
# GEO Knowledge Hub is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: '2.2'

services:
  verdaccio:
    build:
      context: ${PWD}/docker/builder/services/verdaccio/
      dockerfile: ${PWD}/docker/builder/services/verdaccio/Dockerfile
    image: verdaccio-registry:5.10.2
    hostname: "verdaccio-registry"
    container_name: "verdaccio-registry"
    network_mode: bridge
    ports:
      - "4873:4873"
