name: build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14.0.0

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (GEO Knowledge Hub)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: geoknowledgehub/geo-knowledge-hub:${{ steps.vars.outputs.tag }}
